# Generated by Django 2.2.5 on 2021-03-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfileInfo', verbose_name='post_author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='likes', to='blog.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_shares',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='shares', to='blog.UserProfileInfo'),
        ),
    ]
