# Generated by Django 2.2.5 on 2021-03-13 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210312_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
